"""Add service_id to Client

Revision ID: 94261d6ace72
Revises: 019994d42e76
Create Date: 2026-03-01 09:57:22.743065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94261d6ace72'
down_revision: Union[str, Sequence[str], None] = '019994d42e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_clients_service_id', 'service_catalog', ['service_id'], ['id'])

    with op.batch_alter_table('service_catalog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_free_visits', sa.Float(), nullable=False, server_default='0.0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_catalog', schema=None) as batch_op:
        batch_op.drop_column('max_free_visits')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clients_service_id', type_='foreignkey')

    # ### end Alembic commands ###
