"""add client invoice fields

Revision ID: b3d5e2a7f1c8
Revises: c1b6f8d9e2a4
Create Date: 2026-04-24 14:05:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b3d5e2a7f1c8'
down_revision = 'c1b6f8d9e2a4'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('personal_address', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('built_up_area', sa.Float(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'built_up_area')
    op.drop_column('clients', 'personal_address')
    # ### end Alembic commands ###
